# Framework configuration
# config.yaml

router:
  host    : "10.3.12.1"
  username: "admin"
  password: "admin"
  port    : 22
  host_key_algorithms:
    - "ssh-rsa"
    - "ssh-dss"

proxy:
  host    : "172.30.16.107"
  username: "my_dev_user"
  password: "my_dev_password"
  port    : 22
  host_key_algorithms:
    - "ssh-rsa"
    - "ssh-dss"

timeouts:
  connection: 30  # Seconds
  command   : 180  # Seconds
  commit    : 600 # Seconds

logging:
  level: "INFO"
  file: "logs/router_test.log"
