# Framework configuration
# config.yaml

router:
  host    : "10.3.12.10"
  username: "root"
  password: "root"
  port    : 22
  host_key_algorithms:
    - "ssh-rsa"
    - "ssh-dss"

proxy:
  host    : "172.30.16.107"
  username: "my_username"
  password: "my_password"
  port    : 22
  host_key_algorithms:
    - "ssh-rsa"
    - "ssh-dss"

logging:
  level: "INFO"
  file: "logs/router.log"
