[package]
name = "isis-neighbor-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap = "1.1.0"
pnet = "0.34.0"
hex = "0.4.3"
log = "0.4"
env_logger = "0.10"
slog = "2.7"
slog-term = "2.9"
slog-async = "2.8"
ctrlc = "3.4"
thiserror = "1.0"